<Project Sdk="Assimalign.Viu.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Assimalign.Viu.Examples.Showcase</RootNamespace>
    <AssemblyName>Assimalign.Viu.Showcase</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <ViuRunAotCompilation Condition="'$(ViuRunAotCompilation)' == ''">false</ViuRunAotCompilation>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ViuRunAotCompilation)' == 'true'">
    <RunAOTCompilation>true</RunAOTCompilation>
  </PropertyGroup>

  <ItemGroup>
    <StaticWebAssetFingerprintPattern Include="JS" Pattern="*.js" Expression="#[.{fingerprint}]!" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Assimalign.Viu.Router" Version="10.0.1-preview.2" />
    <PackageReference Include="Assimalign.Viu.Router.Browser" Version="10.0.1-preview.2" />
  </ItemGroup>
</Project>
